name: Accessibility issue
description: Report an accessibility issue with a Taiwanese public good website
title: "[a11y]: "
labels: ["bug", "triage"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an accessibility issue! See the Readme for additional information.
  - type: textarea
    id: what-happened
    attributes:
      label: What is the accessibility issue?
      placeholder: Tell us what is wrong with the site!
      value: ""
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Please add a screenshot here (if applicable)
      placeholder: Adding a screenshot helps us locating the issue quicker
      value: ""
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the issue?
      placeholder: Make sure to add a starting URL from where you can reproduce the issue 
      value: |
        1. Go to this page: http://...
        2. Click on ...
        3. The issue is now ...
    validations:
      required: true
